### ISSUE TITLE
Issues with data parallel training. 

### ISSUE THREAD

**Issue by timzsu** [cshizhe/vil3dref#3]
Hi @cshizhe, 

I was using NVIDIA RTX3090 with PyTorch 1.12.1 with CUDA 11.3 to launch your code. And I have found some issues with data-parallel training. 

In the code, you wrap the model automatically with DataParallel, but when I am inferencing the model, it throws an error about the unaligned gathering. This is because the last batch is not as big as the others and DataParallel, therefore, gives an error. The error just vanishes if I commented Line 53-55 in ```utils/misc.py```. 

I wonder if it is just an issue with the version of PyTorch or if it is an inherited problem of DataParallel. Is the original code works fine in your environment?

**Comment by cshizhe** [comment]
Hi, Sorry I haven't tested the codes in multi-gpu setting. But it should work fine using **DistributedDataParallel** instead of **DataParallel**. The codes are adapted from my [previous project](https://github.com/cshizhe/VLN-DUET/tree/main/pretrain_src/utils) and work well with multiple gpus. Let me know if you have further problems.

**Comment by SilenKZYoung** [comment]
I also meet the same error, and after deleting Lines 53-55 in misc.py, the error vanishes.

**Comment by cshizhe** [comment]
Thanks. I closed the issue since the problem was solved.
